#!/usr/bin/env bash
# Assemble share-viewer/ from shared static assets (single source of truth for UI).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/share-viewer"
FRAGMENTS="$ROOT/static/fragments"

read_fragment() {
  local name="$1"
  cat "$FRAGMENTS/$name"
}

mkdir -p "$OUT/css" "$OUT/js" "$OUT/fonts"

cp "$ROOT/static/css/styles.css" "$OUT/css/styles.css"
cp "$ROOT/static/css/material-symbols.css" "$OUT/css/material-symbols.css"
cp "$ROOT/static/css/share-overrides.css" "$OUT/css/share-overrides.css"
cp "$ROOT/static/fonts/MaterialSymbolsOutlined.woff2" "$OUT/fonts/MaterialSymbolsOutlined.woff2"

touch "$OUT/.nojekyll"
mkdir -p "$OUT/.github/workflows"
cp "$ROOT/scripts/share-viewer-pages.yml" "$OUT/.github/workflows/pages.yml"

mkdir -p "$OUT/js/photoSurface"

cp "$ROOT/static/js/gridLayout.js" "$OUT/js/gridLayout.js"
cp "$ROOT/static/js/viewCapabilities.js" "$OUT/js/viewCapabilities.js"
cp "$ROOT/static/js/shareBoot.js" "$OUT/js/shareBoot.js"
cp "$ROOT/static/js/shareResolveClient.js" "$OUT/js/shareResolveClient.js"
cp "$ROOT/static/js/lightboxVideoControls.js" "$OUT/js/lightboxVideoControls.js"
cp "$ROOT/static/js/photoSurface/"*.js "$OUT/js/photoSurface/"

rm -f "$OUT/css/share.css" "$OUT/js/app.js"

cat > "$OUT/index.html" <<'HTML_HEAD'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shared Photos</title>
    <!-- Generated by scripts/build-share-viewer.sh — do not edit by hand -->
    <link rel="stylesheet" href="css/material-symbols.css?v=1" />
    <link rel="stylesheet" href="css/styles.css?v=18" />
    <link rel="stylesheet" href="css/share-overrides.css?v=14" />
  </head>
  <body class="share-view surface-load-active surface-load-phase-loading filter-chip-rail-visible">
    <div id="appChromeMount">
      <div id="appBarMount">
HTML_HEAD

read_fragment appBar.html >> "$OUT/index.html"

cat >> "$OUT/index.html" <<'HTML_MID'
      </div>
HTML_MID

read_fragment filterChipRailShare.html >> "$OUT/index.html"

cat >> "$OUT/index.html" <<'HTML_MID2'
    </div>
HTML_MID2

read_fragment utilitiesMenu.html >> "$OUT/index.html"

cat >> "$OUT/index.html" <<'HTML_MAIN'
    <main class="page-main">
      <div class="page-wrapper">
        <h1 class="share-page-title" id="sharePageTitle"></h1>
        <div id="photoContainer"></div>
        <div class="share-empty" id="shareEmpty" hidden>No photos match these filters.</div>
        <div class="share-error-panel" id="shareErrorPanel">
          <div class="share-error" id="shareError" hidden></div>
          <button
            type="button"
            class="btn btn-primary share-error-retry"
            id="shareErrorRetryBtn"
            hidden
          >
            Try again
          </button>
        </div>
      </div>
    </main>
HTML_MAIN

read_fragment lightbox.html >> "$OUT/index.html"

read_fragment surfaceLoadOverlayShareBoot.html >> "$OUT/index.html"

read_fragment toast.html >> "$OUT/index.html"

read_fragment downloadPrepOverlay.html >> "$OUT/index.html"

cat >> "$OUT/index.html" <<'HTML_TAIL'
    <script src="https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js"></script>
    <script src="js/config.js"></script>
    <script src="js/viewCapabilities.js"></script>
    <script src="js/gridLayout.js"></script>
    <script src="js/photoSurface/gridTile.js?v=2"></script>
    <script src="js/photoSurface/gridSelection.js"></script>
    <script src="js/photoSurface/gridInteractions.js"></script>
    <script src="js/photoSurface/appBarVisibility.js"></script>
    <script src="js/photoSurface/chrome.js"></script>
    <script src="js/photoSurface/filterChipLifecycle.js"></script>
    <script src="js/photoSurface/monthGrid.js"></script>
    <script src="js/photoSurface/simpleGrid.js"></script>
    <script src="js/photoSurface/surfaceSkeletonGrid.js"></script>
    <script src="js/photoSurface/shareSkeletonGrid.js"></script>
    <script src="js/photoSurface/photoGrid.js"></script>
    <script src="js/photoSurface/init.js"></script>
    <script src="js/photoSurface/lightboxMediaCache.js"></script>
    <script src="js/photoSurface/lightboxMedia.js"></script>
    <script src="js/photoSurface/lightboxShell.js"></script>
    <script src="js/lightboxVideoControls.js?v=6"></script>
    <script src="js/photoSurface/surfaceLoadOverlay.js"></script>
    <script src="js/photoSurface/surfaceLoadChrome.js"></script>
    <script src="js/photoSurface/datePickerChrome.js?v=2"></script>
    <script src="js/photoSurface/appBarLayout.js?v=4"></script>
    <script src="js/photoSurface/shareDatePicker.js"></script>
    <script src="js/photoSurface/downloadExport.js"></script>
    <script src="js/shareResolveClient.js?v=1"></script>
    <script src="js/shareBoot.js?v=15"></script>
  </body>
</html>
HTML_TAIL

echo "Built share viewer at $OUT"
